os:
  - linux
language: node_js

node_js:
  - "iojs-2"
  - "iojs-3"
  - "4"
  - "5"

install:
  - npm install coveralls

before_script:
  - npm install

script:
  - node_modules/.bin/mocha -R spec tests/*.js

after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls
